// AUTO-GENERATED by scripts/generateContent.mjs — do not edit by hand.
// Source of truth: live DB table(s) emergency_phrases. Regenerate with `npm run gen:content`
// after any dashboard content change, then ship an app/EAS update.
import type { EmergencyGroup } from '../services/api/emergency';

export const EMERGENCY_GROUPS: EmergencyGroup[] = [
  {
    id: 'auto',
    label: 'Auto / cab',
    items: [
      {
        id: 'e1111111-0001-4001-8001-000000000001',
        kannada: 'ಇಲ್ಲಿ ನಿಲ್ಲಿಸಿ',
        transliteration: 'Illi nillisi',
        meaning: 'Stop here',
        audioUrl: null,
      },
      {
        id: 'e1111111-0001-4001-8001-000000000002',
        kannada: 'ಮೀಟರ್ ಹಾಕಿ',
        transliteration: 'Meter haaki',
        meaning: 'Please put the meter on',
        audioUrl: null,
      },
      {
        id: 'e1111111-0001-4001-8001-000000000003',
        kannada: 'ಎಷ್ಟು?',
        transliteration: 'Eshtu?',
        meaning: 'How much is it?',
        audioUrl: null,
      },
    ],
  },
  {
    id: 'trouble',
    label: 'In trouble',
    items: [
      {
        id: 'e1111111-0002-4001-8001-000000000001',
        kannada: 'ದಯವಿಟ್ಟು ಸಹಾಯ ಮಾಡಿ',
        transliteration: 'Dayavittu sahaaya maadi',
        meaning: 'Please help',
        audioUrl: null,
      },
      {
        id: 'e1111111-0002-4001-8001-000000000002',
        kannada: 'ನನಗೆ ಕನ್ನಡ ಬರಲ್ಲ',
        transliteration: 'Nanage Kannada baralla',
        meaning: "I don't know Kannada",
        audioUrl: null,
      },
      {
        id: 'e1111111-0002-4001-8001-000000000003',
        kannada: 'ಸ್ವಲ್ಪ ನಿಧಾನವಾಗಿ',
        transliteration: 'Swalpa nidhanavagi',
        meaning: 'Slowly, please',
        audioUrl: null,
      },
    ],
  },
  {
    id: 'basics',
    label: 'Basics',
    items: [
      {
        id: 'e1111111-0003-4001-8001-000000000001',
        kannada: 'ಎಲ್ಲಿ?',
        transliteration: 'Elli?',
        meaning: 'Where?',
        audioUrl: null,
      },
      {
        id: 'e1111111-0003-4001-8001-000000000002',
        kannada: 'ಬೇಡ',
        transliteration: 'Beda',
        meaning: "No, don't want",
        audioUrl: null,
      },
      {
        id: 'e1111111-0003-4001-8001-000000000003',
        kannada: 'ಪರವಾಗಿಲ್ಲ',
        transliteration: 'Paravagilla',
        meaning: "It's okay",
        audioUrl: null,
      },
    ],
  },
];
