/**
 * generateContent.mjs — dump live-DB content into bundled TS constants
 * (spec_scalability_offline_fixes Phases 2–3).
 *
 * The live DB is the content source of truth (repo seed SQL has drifted);
 * this script regenerates the app's offline bundles from it. Re-run after
 * any content change in the dashboard, then ship an app/EAS update.
 *
 * Usage:
 *   npm run gen:content         (node --env-file=.env scripts/generateContent.mjs)
 *
 * Env: EXPO_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (preferred; anon
 * key cannot read content tables — RLS grants select to `authenticated` only).
 *
 * Outputs (AUTO-GENERATED — never hand-edit):
 *   constants/emergencyPhrases.ts
 *   constants/games/oppositesItems.ts
 *   constants/games/dictationItems.ts
 *   constants/games/quickQuizItems.ts
 *   constants/games/conversationScenarios.ts
 *
 * Item row UUIDs are copied verbatim — *_progress rows and the
 * record_*_attempt RPCs key on them, so they must match the DB exactly.
 */
import { createClient } from '@supabase/supabase-js';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const url = process.env.EXPO_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('Missing EXPO_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}
const db = createClient(url, key, { auth: { persistSession: false } });

const HEADER = (source) => `// AUTO-GENERATED by scripts/generateContent.mjs — do not edit by hand.
// Source of truth: live DB table(s) ${source}. Regenerate with \`npm run gen:content\`
// after any dashboard content change, then ship an app/EAS update.
`;

async function all(table, select, order) {
  let q = db.from(table).select(select);
  for (const o of order) q = q.order(o, { ascending: true });
  const { data, error } = await q;
  if (error) throw new Error(`${table}: ${error.message}`);
  return data ?? [];
}

function write(rel, content) {
  const file = path.join(ROOT, rel);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`  wrote ${rel}`);
}

const ts = (v) => JSON.stringify(v, null, 2);

async function main() {
  // ---- lessons map (lesson_no -> id), curriculum lessons only ----
  const lessons = (await all('lessons', 'id, lesson_no, slug', ['lesson_no'])).filter(
    (l) => typeof l.lesson_no === 'number' && l.lesson_no > 0,
  );
  const noById = new Map(lessons.map((l) => [l.id, l.lesson_no]));
  console.log(`lessons: ${lessons.length}`);

  // ---- emergency phrases (mirrors services/api/emergency.ts grouping) ----
  const GROUP_LABELS = { auto: 'Auto / cab', trouble: 'In trouble', basics: 'Basics' };
  const GROUP_ORDER = ['auto', 'trouble', 'basics'];
  {
    const rows = await all(
      'emergency_phrases',
      'id, category, kannada, transliteration, meaning, audio_url, sort_order',
      ['category', 'sort_order'],
    );
    const byCat = new Map();
    for (const r of rows) {
      const bucket = byCat.get(r.category) ?? [];
      bucket.push({
        id: r.id,
        kannada: r.kannada,
        transliteration: r.transliteration,
        meaning: r.meaning,
        audioUrl: r.audio_url,
      });
      byCat.set(r.category, bucket);
    }
    const groups = GROUP_ORDER.filter((c) => byCat.has(c)).map((c) => ({
      id: c,
      label: GROUP_LABELS[c] ?? c,
      items: byCat.get(c) ?? [],
    }));
    write(
      'constants/emergencyPhrases.ts',
      `${HEADER('emergency_phrases')}import type { EmergencyGroup } from '../services/api/emergency';

export const EMERGENCY_GROUPS: EmergencyGroup[] = ${ts(groups)};
`,
    );
    console.log(`emergency_phrases: ${rows.length} rows, ${groups.length} groups`);

    // audio-coverage check against the bundled manifest (same normalize as
    // services/audio/bundledAudio.ts)
    const normalize = (t) =>
      t
        .replace(/\[name\]/g, '')
        .normalize('NFC')
        .replace(/\s+/g, ' ')
        .trim();
    const manifestSrc = readFileSync(path.join(ROOT, 'constants/audioManifest.ts'), 'utf8');
    const missing = rows.filter((r) => !manifestSrc.includes(`'${normalize(r.kannada)}'`));
    console.log(
      missing.length
        ? `  ! ${missing.length} phrase(s) without bundled audio (device TTS fallback): ${missing.map((m) => m.meaning).join('; ')}`
        : '  all phrases have bundled audio',
    );
  }

  // ---- per-lesson game items (sort_order > 0 mirrors the app queries) ----
  const byLesson = (rows, map) => {
    const out = {};
    for (const r of rows) {
      const lessonNo = noById.get(r.lesson_id);
      if (!lessonNo || !(r.sort_order > 0)) continue;
      (out[lessonNo] ??= []).push(map(r, lessonNo));
    }
    return out;
  };

  {
    const rows = await all(
      'opposites_items',
      'id, lesson_id, sort_order, word, opposite, transliteration, meaning, section, options_json',
      ['sort_order'],
    );
    const grouped = byLesson(rows, (r, lessonNo) => ({
      id: r.id,
      lessonId: r.lesson_id,
      lessonNo,
      sortOrder: r.sort_order,
      word: r.word,
      opposite: r.opposite,
      transliteration: r.transliteration,
      meaning: r.meaning,
      section: r.section,
      options: r.options_json ?? [],
    }));
    write(
      'constants/games/oppositesItems.ts',
      `${HEADER('opposites_items')}import type { OppositesItem } from '../../services/api/games/opposites';

export const OPPOSITES_ITEMS_BY_LESSON: Record<number, OppositesItem[]> = ${ts(grouped)};
`,
    );
    console.log(`opposites_items: ${rows.length} rows`);
  }

  {
    const rows = await all(
      'dictation_items',
      'id, lesson_id, sort_order, expected_answer, accepted_json, phonetic, audio_url, section',
      ['sort_order'],
    );
    const grouped = byLesson(rows, (r, lessonNo) => ({
      id: r.id,
      lessonId: r.lesson_id,
      lessonNo,
      sortOrder: r.sort_order,
      expectedAnswer: r.expected_answer,
      acceptedSpellings: r.accepted_json ?? [],
      phonetic: r.phonetic,
      audioUrl: r.audio_url,
      section: r.section,
    }));
    write(
      'constants/games/dictationItems.ts',
      `${HEADER('dictation_items')}import type { DictationItem } from '../../services/api/games/dictation';

export const DICTATION_ITEMS_BY_LESSON: Record<number, DictationItem[]> = ${ts(grouped)};
`,
    );
    console.log(`dictation_items: ${rows.length} rows`);
  }

  {
    const rows = await all(
      'quick_quiz_items',
      'id, lesson_id, sort_order, kannada, transliteration, meaning, section',
      ['sort_order'],
    );
    const grouped = byLesson(rows, (r, lessonNo) => ({
      id: r.id,
      lessonId: r.lesson_id,
      lessonNo,
      sortOrder: r.sort_order,
      kannada: r.kannada,
      transliteration: r.transliteration,
      meaning: r.meaning,
      section: r.section,
    }));
    write(
      'constants/games/quickQuizItems.ts',
      `${HEADER('quick_quiz_items')}import type { QuickQuizItem } from '../../services/api/games/quickQuiz';

export const QUICK_QUIZ_ITEMS_BY_LESSON: Record<number, QuickQuizItem[]> = ${ts(grouped)};
`,
    );
    console.log(`quick_quiz_items: ${rows.length} rows`);
  }

  // ---- conversations: scenarios + turns, grouped (mirrors conversations.ts) ----
  {
    const scenarios = await all(
      'conversation_scenarios',
      'id, lesson_id, sort_order, title, section',
      ['sort_order'],
    );
    const items = await all(
      'conversation_items',
      'id, scenario_id, turn_index, speaker_line_kn, speaker_line_en, options_json, correct_option_id',
      ['turn_index'],
    );
    const turnsByScenario = new Map();
    for (const r of items) {
      const turn = {
        id: r.id,
        scenarioId: r.scenario_id,
        turnIndex: r.turn_index,
        speakerLineKn: r.speaker_line_kn,
        speakerLineEn: r.speaker_line_en,
        options: r.options_json ?? [],
        correctOptionId: r.correct_option_id,
      };
      const list = turnsByScenario.get(r.scenario_id);
      if (list) list.push(turn);
      else turnsByScenario.set(r.scenario_id, [turn]);
    }
    const grouped = {};
    for (const s of scenarios) {
      const lessonNo = noById.get(s.lesson_id);
      const turns = turnsByScenario.get(s.id) ?? [];
      if (!lessonNo || turns.length === 0) continue;
      (grouped[lessonNo] ??= []).push({
        id: s.id,
        sortOrder: s.sort_order,
        title: s.title,
        section: s.section,
        turns,
      });
    }
    write(
      'constants/games/conversationScenarios.ts',
      `${HEADER('conversation_scenarios + conversation_items')}import type { ConversationScenario } from '../../services/api/games/conversations';

export const CONVERSATION_SCENARIOS_BY_LESSON: Record<number, ConversationScenario[]> = ${ts(grouped)};
`,
    );
    console.log(`conversation_scenarios: ${scenarios.length}, turns: ${items.length}`);
  }

  console.log('done.');
}

main().catch((e) => {
  console.error('FATAL:', e.message);
  process.exit(1);
});
