import type { Lesson } from './legacy';

export const lesson02Numbers: Lesson = {
  id: 'lesson-02-numbers',
  title: 'Numbers 1–10',
  subtitle: 'Count like a local at the market',
  level: 1,
  estimatedMinutes: 7,
  type: 'lesson',
  culturalNote:
    'Knowing numbers in Kannada is a superpower at local markets. Vendors light up when you count in Kannada — it\'s a sign of effort and respect.',
  words: [
    {
      id: 'w-02-01',
      kannadaScript: 'ಒಂದು',
      transliteration: 'Ondu',
      meaning: 'One',
      audioUrl: 'lesson_02_ondu.mp3',
    },
    {
      id: 'w-02-02',
      kannadaScript: 'ಎರಡು',
      transliteration: 'Eradu',
      meaning: 'Two',
      audioUrl: 'lesson_02_eradu.mp3',
    },
    {
      id: 'w-02-03',
      kannadaScript: 'ಮೂರು',
      transliteration: 'Mooru',
      meaning: 'Three',
      audioUrl: 'lesson_02_mooru.mp3',
    },
    {
      id: 'w-02-04',
      kannadaScript: 'ನಾಲ್ಕು',
      transliteration: 'Naaku',
      meaning: 'Four',
      audioUrl: 'lesson_02_naaku.mp3',
    },
    {
      id: 'w-02-05',
      kannadaScript: 'ಐದು',
      transliteration: 'Aidu',
      meaning: 'Five',
      audioUrl: 'lesson_02_aidu.mp3',
    },
    {
      id: 'w-02-06',
      kannadaScript: 'ಆರು',
      transliteration: 'Aaru',
      meaning: 'Six',
      audioUrl: 'lesson_02_aaru.mp3',
    },
    {
      id: 'w-02-07',
      kannadaScript: 'ಏಳು',
      transliteration: 'Eelu',
      meaning: 'Seven',
      audioUrl: 'lesson_02_eelu.mp3',
    },
    {
      id: 'w-02-08',
      kannadaScript: 'ಎಂಟು',
      transliteration: 'Entu',
      meaning: 'Eight',
      audioUrl: 'lesson_02_entu.mp3',
    },
    {
      id: 'w-02-09',
      kannadaScript: 'ಒಂಬತ್ತು',
      transliteration: 'Ombattu',
      meaning: 'Nine',
      audioUrl: 'lesson_02_ombattu.mp3',
    },
    {
      id: 'w-02-10',
      kannadaScript: 'ಹತ್ತು',
      transliteration: 'Hattu',
      meaning: 'Ten',
      audioUrl: 'lesson_02_hattu.mp3',
    },
  ],
  quiz: [
    {
      id: 'q-02-01',
      type: 'mcq',
      question: 'What is "Five" in Kannada?',
      options: ['Mooru', 'Aidu', 'Naaku', 'Aaru'],
      correctAnswer: 'Aidu',
      explanation: 'Aidu means five in Kannada.',
    },
    {
      id: 'q-02-02',
      type: 'translate',
      question: 'What number does "Ombattu" represent?',
      options: ['Seven', 'Eight', 'Nine', 'Ten'],
      correctAnswer: 'Nine',
      explanation: 'Ombattu is nine in Kannada.',
    },
    {
      id: 'q-02-03',
      type: 'mcq',
      question: 'How do you say "Three" in Kannada?',
      options: ['Eradu', 'Mooru', 'Ondu', 'Hattu'],
      correctAnswer: 'Mooru',
      explanation: 'Mooru means three in Kannada.',
    },
  ],
};
