// AUTO-GENERATED by scripts/generateContent.mjs — do not edit by hand.
// Source of truth: live DB table(s) conversation_scenarios + conversation_items. Regenerate with `npm run gen:content`
// after any dashboard content change, then ship an app/EAS update.
import type { ConversationScenario } from '../../services/api/games/conversations';

export const CONVERSATION_SCENARIOS_BY_LESSON: Record<number, ConversationScenario[]> = {
  '1': [
    {
      id: '246d02fc-1430-451a-9e4a-f3f9578a2c5b',
      sortOrder: 1,
      title: 'Greeting a neighbour',
      section: '1c',
      turns: [
        {
          id: 'f7f06eea-cf01-4881-862b-108e5b3aa1d7',
          scenarioId: '246d02fc-1430-451a-9e4a-f3f9578a2c5b',
          turnIndex: 1,
          speakerLineKn: 'ನಮಸ್ಕಾರ!',
          speakerLineEn: 'Hello!',
          options: [
            {
              en: 'Hello / greetings',
              id: 'a',
              kn: 'ನಮಸ್ಕಾರ',
              tr: 'namaskāra',
            },
            {
              en: 'house',
              id: 'b',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
            {
              en: 'name',
              id: 'c',
              kn: 'ಹೆಸರು',
              tr: 'hesaru',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: 'e5c920e5-e725-4178-9ed9-f0029214cf54',
          scenarioId: '246d02fc-1430-451a-9e4a-f3f9578a2c5b',
          turnIndex: 2,
          speakerLineKn: 'ಹೇಗಿದ್ದೀರ?',
          speakerLineEn: 'How are you? (respectful)',
          options: [
            {
              en: 'I am fine',
              id: 'a',
              kn: 'ಚೆನ್ನಾಗಿದ್ದೇನೆ',
              tr: 'chennāgiddēne',
            },
            {
              en: 'you (respectful)',
              id: 'b',
              kn: 'ನೀವು',
              tr: 'nīvu',
            },
            {
              en: 'you (neutral)',
              id: 'c',
              kn: 'ನೀನು',
              tr: 'nīnu',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: '8496c5d1-9b16-4cc1-902f-f78c038c5650',
          scenarioId: '246d02fc-1430-451a-9e4a-f3f9578a2c5b',
          turnIndex: 3,
          speakerLineKn: 'ನೀವು ಚೆನ್ನಾಗಿದ್ದೀರಾ?',
          speakerLineEn: 'Are you fine? (respectful)',
          options: [
            {
              en: 'Yes, I am fine',
              id: 'a',
              kn: 'ಹೌದು, ಚೆನ್ನಾಗಿದ್ದೇನೆ',
              tr: 'haudu, chennāgiddēne',
            },
            {
              en: 'name',
              id: 'b',
              kn: 'ಹೆಸರು',
              tr: 'hesaru',
            },
            {
              en: 'house',
              id: 'c',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
          ],
          correctOptionId: 'a',
        },
      ],
    },
    {
      id: 'a4461fb0-3d59-49f4-8c85-47d763795bdc',
      sortOrder: 2,
      title: 'Meeting a friend',
      section: '1c',
      turns: [
        {
          id: '374d4dc9-f558-4cae-b555-442c883f783b',
          scenarioId: 'a4461fb0-3d59-49f4-8c85-47d763795bdc',
          turnIndex: 1,
          speakerLineKn: 'ನಮಸ್ತೆ!',
          speakerLineEn: 'Hi!',
          options: [
            {
              en: 'Hi / hello',
              id: 'a',
              kn: 'ನಮಸ್ತೆ',
              tr: 'namaste',
            },
            {
              en: 'do not want',
              id: 'b',
              kn: 'ಬೇಡ',
              tr: 'bēḍa',
            },
            {
              en: 'that person',
              id: 'c',
              kn: 'ಅವರು',
              tr: 'avaru',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: '1418e3d9-2d7b-4407-92f5-4cbc8250d68d',
          scenarioId: 'a4461fb0-3d59-49f4-8c85-47d763795bdc',
          turnIndex: 2,
          speakerLineKn: 'ಹೇಗಿದ್ದೀಯ?',
          speakerLineEn: 'How are you? (neutral)',
          options: [
            {
              en: 'I am fine',
              id: 'a',
              kn: 'ಚೆನ್ನಾಗಿದ್ದೇನೆ',
              tr: 'chennāgiddēne',
            },
            {
              en: 'your (respectful)',
              id: 'b',
              kn: 'ನಿಮ್ಮ',
              tr: 'nimma',
            },
            {
              en: 'where',
              id: 'c',
              kn: 'ಎಲ್ಲಿ',
              tr: 'elli',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: 'de0d2cd8-22e5-4506-97de-79ac70680910',
          scenarioId: 'a4461fb0-3d59-49f4-8c85-47d763795bdc',
          turnIndex: 3,
          speakerLineKn: 'ಸರಿ, ನಮಸ್ಕಾರ.',
          speakerLineEn: 'Okay, goodbye.',
          options: [
            {
              en: 'Goodbye',
              id: 'a',
              kn: 'ನಮಸ್ಕಾರ',
              tr: 'namaskāra',
            },
            {
              en: 'name',
              id: 'b',
              kn: 'ಹೆಸರು',
              tr: 'hesaru',
            },
            {
              en: 'house',
              id: 'c',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
          ],
          correctOptionId: 'a',
        },
      ],
    },
  ],
  '2': [
    {
      id: 'c78ccc04-6f26-425a-8079-5c1ec6d3be51',
      sortOrder: 1,
      title: 'Introducing yourself',
      section: '2c',
      turns: [
        {
          id: '0ae47150-6b33-486d-8077-016bdff02507',
          scenarioId: 'c78ccc04-6f26-425a-8079-5c1ec6d3be51',
          turnIndex: 1,
          speakerLineKn: 'ನಿಮ್ಮ ಹೆಸರು ಏನು?',
          speakerLineEn: 'What is your name? (respectful)',
          options: [
            {
              en: 'I am [name]',
              id: 'a',
              kn: 'ನಾನು ಪ್ರಿಯಾ',
              tr: 'nānu [name]',
            },
            {
              en: 'house',
              id: 'b',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
            {
              en: 'that person',
              id: 'c',
              kn: 'ಅವರು',
              tr: 'avaru',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: 'e3073adf-623c-434c-9a11-c7ff1c9c3244',
          scenarioId: 'c78ccc04-6f26-425a-8079-5c1ec6d3be51',
          turnIndex: 2,
          speakerLineKn: 'ನಿಮ್ಮ ಮನೆ ಎಲ್ಲಿ?',
          speakerLineEn: 'Where is your house?',
          options: [
            {
              en: 'Here',
              id: 'a',
              kn: 'ಇಲ್ಲಿ',
              tr: 'illi',
            },
            {
              en: 'name',
              id: 'b',
              kn: 'ಹೆಸರು',
              tr: 'hesaru',
            },
            {
              en: 'you (respectful)',
              id: 'c',
              kn: 'ನೀವು',
              tr: 'nīvu',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: '89d23ab6-9c75-4466-b543-ac9a1b9c37b9',
          scenarioId: 'c78ccc04-6f26-425a-8079-5c1ec6d3be51',
          turnIndex: 3,
          speakerLineKn: 'ಸರಿ, ನಮಸ್ಕಾರ.',
          speakerLineEn: 'Okay, goodbye.',
          options: [
            {
              en: 'Goodbye',
              id: 'a',
              kn: 'ನಮಸ್ಕಾರ',
              tr: 'namaskāra',
            },
            {
              en: 'I',
              id: 'b',
              kn: 'ನಾನು',
              tr: 'nānu',
            },
            {
              en: 'house',
              id: 'c',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
          ],
          correctOptionId: 'a',
        },
      ],
    },
    {
      id: 'd74ecb5f-88db-44ba-92ea-65183d5776c0',
      sortOrder: 2,
      title: 'Asking about people',
      section: '2c',
      turns: [
        {
          id: 'd6657364-ea20-4593-b848-7aaf91f8318f',
          scenarioId: 'd74ecb5f-88db-44ba-92ea-65183d5776c0',
          turnIndex: 1,
          speakerLineKn: 'ನಿನ್ನ ಹೆಸರು ಏನು?',
          speakerLineEn: 'What is your name? (neutral)',
          options: [
            {
              en: 'I am [name]',
              id: 'a',
              kn: 'ನಾನು ರವಿ',
              tr: 'nānu [name]',
            },
            {
              en: 'your (respectful)',
              id: 'b',
              kn: 'ನಿಮ್ಮ',
              tr: 'nimma',
            },
            {
              en: 'house',
              id: 'c',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: 'adb60759-3073-4c61-94df-c86ef5957bf0',
          scenarioId: 'd74ecb5f-88db-44ba-92ea-65183d5776c0',
          turnIndex: 2,
          speakerLineKn: 'ಇವಳು ಯಾರು?',
          speakerLineEn: 'Who is she?',
          options: [
            {
              en: 'She is Priya',
              id: 'a',
              kn: 'ಇವಳು ಪ್ರಿಯಾ',
              tr: 'ivaḷu priyā',
            },
            {
              en: 'that person (he)',
              id: 'b',
              kn: 'ಅವನು',
              tr: 'avanu',
            },
            {
              en: 'house',
              id: 'c',
              kn: 'ಮನೆ',
              tr: 'mane',
            },
          ],
          correctOptionId: 'a',
        },
        {
          id: '3476a11e-5bde-40ea-8b52-df276933729b',
          scenarioId: 'd74ecb5f-88db-44ba-92ea-65183d5776c0',
          turnIndex: 3,
          speakerLineKn: 'ಸರಿ!',
          speakerLineEn: 'Okay!',
          options: [
            {
              en: 'Goodbye',
              id: 'a',
              kn: 'ನಮಸ್ಕಾರ',
              tr: 'namaskāra',
            },
            {
              en: 'name',
              id: 'b',
              kn: 'ಹೆಸರು',
              tr: 'hesaru',
            },
            {
              en: 'you (neutral)',
              id: 'c',
              kn: 'ನೀನು',
              tr: 'nīnu',
            },
          ],
          correctOptionId: 'a',
        },
      ],
    },
  ],
};
